### ISSUE TITLE
redis-server: No such file or directory

### ISSUE THREAD

**Issue by Hscpro** [zkeq/Busuanzi_backend_self#3]
hi~ 在自建时日志报错 redis-server: No such file or directory

redis-server不是个可执行文件？

![image](https://user-images.githubusercontent.com/13926044/177296888-215017b6-4cad-4bef-9658-fb9abb9bb200.png)

**Comment by Hscpro** [comment]
Dockerfile 文件
```
FROM python:3.9.5-alpine

WORKDIR /home/busuanzi

RUN pip install "redis==4.1.4"
RUN pip install "uvicorn==0.17.6"
RUN pip install "fastapi==0.75.0"
RUN pip install "requests==2.25.1"


ENTRYPOINT ["python3", "main.py"]

EXPOSE 4000
CMD ["/bin/sh"]
```

docker 内的日志
![image](https://user-images.githubusercontent.com/13926044/177299733-de0ac4bf-e286-4179-8774-e89a1e2aa354.png)

**Comment by zkeq** [comment]
本项目内的 `redis-server` 是适配的 `replit` 的架构...

如果是自己服务器部署的话，自行启动一个 `redis` 并注释相关代码吧

https://github.com/zkeq/Busuanzi_backend_self/blob/3586266ba8fcbc09d704c5c294e41ad43c718f37/main.py#L55-L58

本项目近期将增加对于 `docker` 的支持...

> 不清楚这个报错什么原因...我电脑带不起来 `docker` 
> 
> 我的服务器是直接跑在 `screen` 里面的...
>
> 服务器的 `redis` 直接用
> 
> https://redis.io/docs/getting-started/installation/install-redis-on-linux/#install-on-ubuntudebian
> 
> ```bash
> sudo apt-get update
> sudo apt-get install redis
> ```
> 
> 等新电脑到了我支持一下对于 `docker` 的适配

**Comment by soxft** [comment]
可以尝试再开一个 redis 的容器, 使用 `--link` 将其进行关联, 修改下`main.py` 删除 启动redis相关的命令，并修改 redis连接至 启动的容器就行了

**Comment by Hscpro** [comment]
Dockerfile:
```
FROM python:3.9.5-alpine
WORKDIR /home/busuanzi
RUN pip install "redis==4.1.4"
RUN pip install "uvicorn==0.17.6"
RUN pip install "fastapi==0.75.0"
RUN pip install "requests==2.25.1"
ENTRYPOINT ["python3", "main.py"]
EXPOSE 4000
CMD ["/bin/sh"]
```
docker-compose:
```
version: "3"
services:

  bsz_redis:
    image: redis:latest
    container_name: bsz_redis
    restart: always
    networks:
      - bsz_net
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - "/root/docker/busuanzi/data:/data"

  busuanzi:
    image: busuanzi:latest
    container_name: busuanzi
    restart: always
    networks:
      - bsz_net
    ports:
      - 0.0.0.0:22322:8080/tcp
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - "/root/docker/busuanzi:/home/busuanzi"

networks:
  bsz_net:
    driver: "bridge"
```

按以上方案，并将``main.py``内的redis服务器地址改为``bsz_redis``，正常启动。

![image](https://user-images.githubusercontent.com/13926044/177733442-bf52c65e-a5ba-4283-b842-edd1234485f8.png)
